# Generated by Django 5.2.1 on 2025-06-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desmatamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('regiao', models.CharField(max_length=100)),
                ('hectares', models.FloatField()),
            ],
        ),
    ]
